// List of NASDAQ-100 equities (symbol and name)
export const NASDAQ100 = [
  { symbol: 'AAPL', name: 'Apple Inc.' },
  { symbol: 'MSFT', name: 'Microsoft Corporation' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. (Class A)' },
  { symbol: 'GOOG', name: 'Alphabet Inc. (Class C)' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation' },
  { symbol: 'META', name: 'Meta Platforms Inc.' },
  { symbol: 'TSLA', name: 'Tesla Inc.' },
  { symbol: 'PEP', name: 'PepsiCo Inc.' },
  { symbol: 'AVGO', name: 'Broadcom Inc.' },
  { symbol: 'COST', name: 'Costco Wholesale Corporation' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.' },
  { symbol: 'ADBE', name: 'Adobe Inc.' },
  { symbol: 'TMUS', name: 'T-Mobile US Inc.' },
  { symbol: 'TXN', name: 'Texas Instruments Incorporated' },
  { symbol: 'AMGN', name: 'Amgen Inc.' },
  { symbol: 'QCOM', name: 'QUALCOMM Incorporated' },
  { symbol: 'INTC', name: 'Intel Corporation' },
  { symbol: 'HON', name: 'Honeywell International Inc.' },
  { symbol: 'SBUX', name: 'Starbucks Corporation' },
  { symbol: 'AMD', name: 'Advanced Micro Devices Inc.' },
  { symbol: 'AMAT', name: 'Applied Materials Inc.' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.' },
  { symbol: 'INTU', name: 'Intuit Inc.' },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc.' },
  { symbol: 'MDLZ', name: 'Mondelez International Inc.' },
  { symbol: 'ADI', name: 'Analog Devices Inc.' },
  { symbol: 'GILD', name: 'Gilead Sciences Inc.' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals Inc.' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Incorporated' },
  { symbol: 'FISV', name: 'Fiserv Inc.' },
  { symbol: 'MU', name: 'Micron Technology Inc.' },
  { symbol: 'LRCX', name: 'Lam Research Corporation' },
  { symbol: 'ADP', name: 'Automatic Data Processing Inc.' },
  { symbol: 'MAR', name: 'Marriott International Inc.' },
  { symbol: 'KDP', name: 'Keurig Dr Pepper Inc.' },
  { symbol: 'CTSH', name: 'Cognizant Technology Solutions Corporation' },
  { symbol: 'MNST', name: 'Monster Beverage Corporation' },
  { symbol: 'ASML', name: 'ASML Holding N.V.' },
  { symbol: 'EXC', name: 'Exelon Corporation' },
  { symbol: 'ADSK', name: 'Autodesk Inc.' },
  { symbol: 'MELI', name: 'MercadoLibre Inc.' },
  { symbol: 'AEP', name: 'American Electric Power Company Inc.' },
  { symbol: 'IDXX', name: 'IDEXX Laboratories Inc.' },
  { symbol: 'CDNS', name: 'Cadence Design Systems Inc.' },
  { symbol: 'ORLY', name: "O'Reilly Automotive Inc." },
  { symbol: 'SNPS', name: 'Synopsys Inc.' },
  { symbol: 'ROST', name: 'Ross Stores Inc.' },
  { symbol: 'WDAY', name: 'Workday Inc.' },
  { symbol: 'PAYX', name: 'Paychex Inc.' },
  { symbol: 'PCAR', name: 'PACCAR Inc.' },
  { symbol: 'CSGP', name: 'CoStar Group Inc.' },
  { symbol: 'XEL', name: 'Xcel Energy Inc.' },
  { symbol: 'DLTR', name: 'Dollar Tree Inc.' },
  { symbol: 'FAST', name: 'Fastenal Company' },
  { symbol: 'BKR', name: 'Baker Hughes Company' },
  { symbol: 'WBA', name: 'Walgreens Boots Alliance Inc.' },
  { symbol: 'EBAY', name: 'eBay Inc.' },
  { symbol: 'SIRI', name: 'Sirius XM Holdings Inc.' },
  { symbol: 'VRSK', name: 'Verisk Analytics Inc.' },
  { symbol: 'CTAS', name: 'Cintas Corporation' },
  { symbol: 'TEAM', name: 'Atlassian Corporation' },
  { symbol: 'ANSS', name: 'ANSYS Inc.' },
  { symbol: 'LCID', name: 'Lucid Group Inc.' },
  { symbol: 'FTNT', name: 'Fortinet Inc.' },
  { symbol: 'BIIB', name: 'Biogen Inc.' },
  { symbol: 'PDD', name: 'PDD Holdings Inc.' },
  { symbol: 'MRVL', name: 'Marvell Technology Inc.' },
  { symbol: 'DDOG', name: 'Datadog Inc.' },
  { symbol: 'CPRT', name: 'Copart Inc.' },
  { symbol: 'CHTR', name: 'Charter Communications Inc.' },
  { symbol: 'ALGN', name: 'Align Technology Inc.' },
  { symbol: 'ZS', name: 'Zscaler Inc.' },
  { symbol: 'OKTA', name: 'Okta Inc.' },
  { symbol: 'SPLK', name: 'Splunk Inc.' },
  { symbol: 'DOCU', name: 'DocuSign Inc.' },
  { symbol: 'SGEN', name: 'Seagen Inc.' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings Inc.' },
  { symbol: 'MCHP', name: 'Microchip Technology Incorporated' },
  { symbol: 'DLR', name: 'Digital Realty Trust Inc.' },
  { symbol: 'VRSN', name: 'Verisign Inc.' },
  { symbol: 'SWKS', name: 'Skyworks Solutions Inc.' },
  { symbol: 'TTD', name: 'The Trade Desk Inc.' },
  { symbol: 'ON', name: 'ON Semiconductor Corporation' },
  { symbol: 'BIDU', name: 'Baidu Inc.' },
  { symbol: 'NTES', name: 'NetEase Inc.' },
  { symbol: 'JD', name: 'JD.com Inc.' },
  { symbol: 'KHC', name: 'The Kraft Heinz Company' },
  { symbol: 'FOX', name: 'Fox Corporation (Class B)' },
  { symbol: 'FOXA', name: 'Fox Corporation (Class A)' },
  { symbol: 'LULU', name: 'Lululemon Athletica Inc.' },
  { symbol: 'WBD', name: 'Warner Bros. Discovery Inc.' },
  { symbol: 'CMCSA', name: 'Comcast Corporation' },

];
